---
name: Lidarr
version: pr-plugins
slug: lidarr
description: Looks and smells like Sonarr but made for music
url: https://github.com/gr1los/addon-lidarr/
image: ghcr.io/gr1los/addon-lidarr
logo: https://raw.githubusercontent.com/gr1los/addon-lidarr/main/lidarr/logo.png
maintainers:
  - gr1los
webui: http://[HOST]:[PORT:8686]
init: false
arch:
  - aarch64
  - amd64
  - armv7
map:
  - addon_config:rw
  - share:rw
  - media:rw
ports:
  8686/tcp: 8686
